# Generated by Django 4.2.4 on 2023-08-25 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('profilresim', models.FileField(blank=True, default='userpic/default.jpg', upload_to='userpic/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iha',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=50)),
                ('agirlik', models.IntegerField(null=True)),
                ('tanitim', models.TextField(max_length=2000)),
                ('resim', models.FileField(upload_to='ihapic/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baykarapp.kategori')),
                ('kiralanacak', models.ManyToManyField(related_name='favori', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
