# Generated by Django 4.2.4 on 2023-08-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='kategoriresim',
            field=models.FileField(blank=True, upload_to='kategoripic/'),
        ),
    ]
