# Generated by Django 4.2.4 on 2023-08-26 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykarapp', '0003_iha_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='kiralama',
            field=models.ManyToManyField(null=True, related_name='kiralama', to=settings.AUTH_USER_MODEL),
        ),
    ]
