# Generated by Django 4.2.4 on 2023-08-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykarapp', '0004_iha_kiralama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='kiralama',
        ),
    ]
